language: python
python:
    - 3.5
    - 3.6

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest pytest-cov

  - python setup.py install

build:
  ci:
    # Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    # Run test and code coverage and output results to the right folder
    - pytest --junitxml=shippable/testresults/nosetests.xml
    - pytest --cov=optimal_nod_combo --cov-report=xml:shippable/codecoverage/coverage.xml --durations=10
    # - pytest --cov=optimal_nod_combo --cov-report term-missing

# after_success:
  #- coveralls -i
  #- codeclimate-test-reporter
  #- coverage xml -i
  #- python-codacy-coverage -r coverage.xml
