language: python
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8

before_install:
  # http://conda.pydata.org/docs/travis.html
  - travis_retry sudo apt-get update
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a

cache:
  directories:
    - $HOME/.cache/pip

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy astropy
  - source activate test-environment

  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest pytest-cov

  - python setup.py install

build:
  ci:
    # Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    # Run test and code coverage and output results to the right folder
    - pytest --junitxml=shippable/testresults/nosetests.xml
    - pytest --cov=optimal_nod_combo --cov-report=xml:shippable/codecoverage/coverage.xml --durations=10
    # - pytest --cov=optimal_nod_combo --cov-report term-missing

# after_success:
  #- coveralls -i
  #- codeclimate-test-reporter
  #- coverage xml -i
  #- python-codacy-coverage -r coverage.xml
